"use client";

import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import * as yup from "yup";
import Button from "@/components/common/button";
import Input from "@/components/common/input";
import Select from "@/components/common/select";
import Loading from "@/components/common/loading";

/**
 * Create Student Form Component
 *
 * Reusable form component for creating new student accounts.
 * Uses React Hook Form for form state management and Yup for validation.
 *
 * Features:
 * - Client-side validation with helpful error messages
 * - Auto-reset form after successful submission
 * - Loading state during submission
 * - Optional fields with sensible defaults
 *
 * Form Fields:
 * - Full Name (required, 3-100 characters)
 * - Email (required, must be valid email format)
 * - Password (required, minimum 6 characters)
 * - Roll Number (optional, auto-generated by backend if not provided)
 * - Current Semester (optional, dropdown 1-8, defaults to 1)
 * - Program (optional, dropdown of available programs, defaults to "BS Computer Science")
 *
 * @component
 * @param {Function} onSubmit - Callback function called with form data on submit
 * @param {Function} onCancel - Callback function called when cancel button is clicked
 * @param {boolean} [loading=false] - Loading state to disable form during submission
 * @returns {JSX.Element} Student creation form
 */

/**
 * Yup validation schema for student creation
 * 
 * Defines validation rules for all form fields.
 * Used by React Hook Form via yupResolver.
 */
const createStudentSchema = yup.object().shape({
  fullName: yup
    .string()
    .required("Full name is required")
    .min(3, "Full name must be at least 3 characters")
    .max(100, "Full name must be less than 100 characters"),
  email: yup
    .string()
    .required("Email is required")
    .email("Please enter a valid email address"),
  password: yup
    .string()
    .required("Password is required")
    .min(6, "Password must be at least 6 characters"),
  rollNumber: yup.string().optional(),
  currentSemester: yup.number().optional().min(1).max(8),
  program: yup.string().optional(),
});

export default function CreateStudentForm({
  onSubmit,
  onCancel,
  loading = false,
}) {
  /**
   * React Hook Form setup
   * 
   * - register: Register form inputs with validation
   * - handleSubmit: Handle form submission with validation
   * - errors: Validation error messages
   * - reset: Reset form to default values
   */
  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
  } = useForm({
    resolver: yupResolver(createStudentSchema), // Use Yup for validation
    defaultValues: {
      fullName: "",
      email: "",
      password: "",
      rollNumber: "",
      currentSemester: "1", // Default to semester 1
      program: "BS Computer Science", // Default program
    },
  });

  /**
   * Handle form submission
   * 
   * Transforms form data before passing to parent component:
   * - Converts currentSemester from string to number (if provided)
   * - Removes undefined values
   * - Resets form after successful submission
   * 
   * @async
   * @function handleFormSubmit
   * @param {Object} data - Form data from React Hook Form
   * @returns {Promise<void>}
   */
  const handleFormSubmit = async (data) => {
    // Convert currentSemester from string to number for API
    const submitData = {
      ...data,
      currentSemester: data.currentSemester
        ? parseInt(data.currentSemester, 10)
        : undefined,
    };
    
    // Call parent's onSubmit handler with transformed data
    await onSubmit(submitData);
    
    // Reset form to default values after successful submission
    reset();
  };

  /**
   * Handle cancel button click
   * 
   * Resets form and calls parent's onCancel handler.
   * This ensures form is clean if user reopens the modal.
   */
  const handleCancel = () => {
    reset(); // Clear form data
    onCancel(); // Close modal (handled by parent)
  };

  return (
    <form onSubmit={handleSubmit(handleFormSubmit)} className="space-y-4">
      <Input
        label="Full Name"
        name="fullName"
        placeholder="Enter student full name"
        register={register}
        error={errors.fullName?.message}
        required
      />

      <Input
        label="Email Address"
        name="email"
        type="email"
        placeholder="Enter student email"
        register={register}
        error={errors.email?.message}
        required
      />

      <Input
        label="Password"
        name="password"
        type="password"
        placeholder="Enter password (min 6 characters)"
        register={register}
        error={errors.password?.message}
        required
      />

      <Input
        label="Roll Number (Optional)"
        name="rollNumber"
        placeholder="Auto-generated if not provided"
        register={register}
        error={errors.rollNumber?.message}
      />

      <Select
        label="Current Semester (Optional)"
        name="currentSemester"
        register={register}
        placeholder="Select semester"
        error={errors.currentSemester?.message}
        options={[1, 2, 3, 4, 5, 6, 7, 8].map((sem) => ({
          value: sem.toString(),
          label: `Semester ${sem}`,
        }))}
      />

      <Select
        label="Program (Optional)"
        name="program"
        register={register}
        placeholder="Select program"
        error={errors.program?.message}
        options={[
          "BS Computer Science",
          "BS Software Engineering",
          "BS Information Technology",
          "BS Electrical Engineering",
          "BS Mechanical Engineering",
          "BS Civil Engineering",
          "BS Business Administration",
          "BS Mathematics",
          "BS Physics",
          "BS Chemistry",
          "BS Biology",
          "BA English",
          "BA History",
          "BS Psychology",
        ]}
      />

      <div className="flex items-center justify-end space-x-3 pt-4 border-t border-gray-200">
        <Button type="button" variant="outline" onClick={handleCancel}>
          Cancel
        </Button>
        <Button type="submit" disabled={loading}>
          {loading && (
            <span className="mr-2">
              <Loading size="sm" />
            </span>
          )}
          Create Student
        </Button>
      </div>
    </form>
  );
}

